# NexT Theme Comments Settings
giscus:
  enable: false
  repo: alan-zhang-22/alantech
  repo_id: R_kgDOPHi3mQ
  category: Blog Comments
  category_id: DIC_kwDOPHi3mc4Cs10y
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: light
  lang: en
  loading: lazy
